GET http://localhost:3000/posts

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Gopi",
    "password": "vasundhara123"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "name": "Gopi",
    "password": "vasundhara123"
}